Action validation
egal/framework pull request #17
Opened 2022-09-22 07:45 UTC by Krishtalev

2022-09-22 07:55 UTC, vedorofeev commented on php-package/src/Core/ActionCaller/ActionCaller.php
> +        return in_array('nullable', $parameter->getValidationRules());
сделать свойством nullable. при сете добавляется в validation rules

2022-09-22 07:56 UTC, vedorofeev commented on php-package/src/Model/Exceptions/ActionParameterNotFoundException.php
> +        $exception->message = 'ActionParameter ' . $parameter . ' not found!';
сделать одной строкой в " "

2022-09-22 07:57 UTC, vedorofeev commented on php-package/src/Core/ActionCaller/ActionCaller.php
> +            throw new NoValidActionParametersException();
```
throw new ActionCallException('Parameter value ' . $actionParameterKey . ' necessarily!');
```

2022-09-22 08:10 UTC, vedorofeev commented on php-package/src/Model/Traits/SetParametersValidationRules.php
> +        $this->modelMetadata = ModelMetadataManager::getModelMetadata(static::class);
Удалить свойство, использовать статичные данные в конкретном методе

2022-09-22 08:11 UTC, vedorofeev commented on php-package/src/Model/Traits/SetParametersValidationRules.php
> +    private array $parametersValidationRules;
Сделать = []

2022-09-22 08:12 UTC, vedorofeev commented on php-package/src/Model/Traits/SetParametersValidationRules.php
> +trait SetParametersValidationRules
UseActionParametersMetadata

2022-09-22 08:15 UTC, vedorofeev commented on php-package/src/Model/Metadata/AbstractAttributeMetadata.php
> +    protected string $name;
reaadonly

2022-09-22 08:15 UTC, vedorofeev commented on php-package/src/Model/Metadata/AbstractAttributeMetadata.php
> +    protected mixed $type;
readonly

2022-09-22 08:15 UTC, vedorofeev commented on php-package/src/Model/Metadata/AbstractAttributeMetadata.php
> +    public function setName(string $name): self
Удалить

2022-09-22 08:15 UTC, vedorofeev commented on php-package/src/Model/Metadata/AbstractAttributeMetadata.php
> +    public function setType(AttributeType $type): self
удалить

2022-09-22 08:24 UTC, vedorofeev commented on php-package/src/Model/Metadata/AbstractAttributeMetadata.php
> +abstract class AbstractAttributeMetadata
Оставить этот класс, удалить Validated класс

2022-09-22 08:24 UTC, vedorofeev commented on php-package/src/Model/Metadata/AbstractAttributeMetadata.php
> +    protected function __construct(string $name, mixed $type)
конструктор и make ринимает AttributeType $type - типизируем

2022-09-22 08:27 UTC, vedorofeev commented on php-package/src/Model/Metadata/ActionMetadata.php
> +    public function fieldExistOrFail(string $parameterName): bool
parameterExistsOrFail

2022-09-22 08:28 UTC, vedorofeev commented on php-package/src/Model/Metadata/ActionMetadata.php
> +        $actionMetadata['parameters'] = array_map(fn($parameter) => $parameter->toArray(), $this->parameters);
перенести на строку после $actionMetadata['name']

2022-09-22 08:28 UTC, vedorofeev commented on php-package/src/Model/Metadata/ActionMetadata.php
> +        $actionMetadata['parameters'] = array_map(fn($parameter) => $parameter->toArray(), $this->parameters);
Добавить класс 
```
(fn(ParameterMetadata $parameter))
```

2022-09-22 08:29 UTC, vedorofeev commented on php-package/src/Model/Metadata/ActionParameterMetadata.php
> +    protected mixed $defaultValue = null;
ереименовать на  `$default`

2022-09-22 08:29 UTC, vedorofeev commented on php-package/src/Model/Metadata/ActionParameterMetadata.php
> +    protected mixed $defaultValue = null;
добавить `$nullable`

2022-09-22 08:38 UTC, vedorofeev commented on php-package/src/Model/Metadata/ActionParameterMetadata.php
> +    public function setDefaultValue(mixed $defaultValue): self
переименовать на `default()`

2022-09-22 08:38 UTC, vedorofeev commented on php-package/src/Model/Metadata/ActionParameterMetadata.php
> +    public function getDefaultValue(): mixed
переименовать на getDefault()

2022-09-22 11:38 UTC, Krishtalev commented on php-package/src/Model/Metadata/AbstractAttributeMetadata.php
> +abstract class AbstractAttributeMetadata
Удалить этот и переименовать Validated?

2022-09-23 03:21 UTC, vedorofeev commented on php-package/src/Model/Metadata/AbstractAttributeMetadata.php
> +abstract class AbstractAttributeMetadata
Объединить этот и validated в один класс AbstractAttributeMetadata.

2022-09-23 03:22 UTC, vedorofeev commented on php-package/src/Model/Metadata/ActionMetadata.php
> +        $actionMetadata['parameters'] = array_map(fn($parameter) => $parameter->toArray(), $this->parameters);
Указать тип аргумента стрелочной функции

2022-09-23 04:52 UTC, vedorofeev commented on php-package/src/Model/Traits/UseActionParametersMetadata.php
> +    public function setParametersValidationRules(): void
Сделать метод приватным

2022-09-23 04:54 UTC, vedorofeev commented on stand/server/auth-service/app/Models/Employee.php
> +                ActionMetadata::make('update')->addParameters(
Перенести addParameters на новую строку

2022-09-23 04:59 UTC, Krishtalev commented on php-package/src/Model/Metadata/ActionMetadata.php
> +        $actionMetadata['parameters'] = array_map(fn($parameter) => $parameter->toArray(), $this->parameters);
+

2022-09-23 04:59 UTC, Krishtalev commented on php-package/src/Model/Metadata/ActionMetadata.php
> +        $actionMetadata['parameters'] = array_map(fn($parameter) => $parameter->toArray(), $this->parameters);
+

2022-09-23 05:00 UTC, vedorofeev commented on php-package/src/Model/Metadata/ActionMetadata.php
>      protected readonly string $name;
Отступ. Прогнать кодстайлер

2022-09-23 05:03 UTC, vedorofeev commented on php-package/src/Model/Exceptions/ActionParameterNotFoundException.php
> +    protected $message = 'ActionParameter not found!';
Action parameter not found

2022-09-23 05:03 UTC, vedorofeev commented on php-package/src/Model/Exceptions/ActionParameterNotFoundException.php
> +        $exception->message = 'ActionParameter ' . $parameter . ' not found!';
Action parameter

2022-09-23 05:03 UTC, Krishtalev commented on php-package/src/Model/Metadata/AbstractAttributeMetadata.php
> +    protected function __construct(string $name, mixed $type)
+

2022-09-23 05:09 UTC, vedorofeev commented on php-package/src/Model/Traits/UseActionParametersMetadata.php
> +    public function getParametersValidationRules(string $actionName): array
Приватный метод

2022-09-23 05:09 UTC, vedorofeev commented on php-package/src/Model/Traits/UseActionParametersMetadata.php
> +    public function setParameterValidationRules(ActionMetadata $action, ActionParameterMetadata $parameter): void
Приватный метод

2022-09-23 05:14 UTC, vedorofeev commented on php-package/src/Model/Traits/UseActionParametersMetadata.php
> +trait UseActionParametersMetadata
UseActionParameterMetadata

2022-09-23 09:49 UTC, Krishtalev commented on php-package/src/Model/Exceptions/ActionParameterNotFoundException.php
> +    protected $message = 'ActionParameter not found!';
+

2022-09-23 09:49 UTC, Krishtalev commented on php-package/src/Model/Exceptions/ActionParameterNotFoundException.php
> +        $exception->message = 'ActionParameter ' . $parameter . ' not found!';
+

2022-09-23 09:49 UTC, Krishtalev commented on php-package/src/Model/Metadata/ActionMetadata.php
>      protected readonly string $name;
+

2022-09-23 09:49 UTC, Krishtalev commented on php-package/src/Model/Traits/UseActionParametersMetadata.php
> +trait UseActionParametersMetadata
+

2022-09-23 09:50 UTC, Krishtalev commented on php-package/src/Model/Traits/UseActionParametersMetadata.php
> +    public function setParametersValidationRules(): void
+

2022-09-23 09:50 UTC, Krishtalev commented on php-package/src/Model/Traits/UseActionParametersMetadata.php
> +    public function setParameterValidationRules(ActionMetadata $action, ActionParameterMetadata $parameter): void
+

2022-09-23 09:50 UTC, Krishtalev commented on php-package/src/Model/Traits/UseActionParametersMetadata.php
> +    public function getParametersValidationRules(string $actionName): array
Используется в actionCaller

2022-09-23 10:08 UTC, Krishtalev commented on stand/server/auth-service/app/Models/Employee.php
> +                ActionMetadata::make('update')->addParameters(
+

2022-09-26 03:21 UTC, vedorofeev commented on php-package/src/Model/Model.php
>          if (!isset($id)) {
убрать if, на уровне actionUpdate сделать $id обязательным ненулевым параметром

2022-09-26 03:25 UTC, vedorofeev commented on php-package/src/Model/Traits/UseActionParameterMetadata.php
> +    private array $parametersValidationRules = [];
переименовать в validationRules. из названия трейта понятно, что это правила валидации параметров

2022-09-26 03:25 UTC, vedorofeev commented on php-package/src/Model/Traits/UseActionParameterMetadata.php
> +    private array $parametersValidationRules = [];
аналогично остальные методы трейта

2022-09-26 03:28 UTC, vedorofeev commented on php-package/src/Model/Model.php
>          $instance->makeIsInstanceForAction();
нужно убрать валидацию (validateKey) и возможно другие из action'ов
получается дублирование валидации параметров action'ов

2022-09-26 03:39 UTC, vedorofeev commented on php-package/src/Model/Traits/UseActionParameterMetadata.php
> +trait UseActionParameterMetadata
переименовать на UsesActionParameterMetadata

2022-09-27 05:00 UTC, Krishtalev commented on php-package/src/Model/Traits/UseActionParameterMetadata.php
> +trait UseActionParameterMetadata
От трейта отказались

2022-09-27 05:47 UTC, vedorofeev approved these changes

2022-09-27 05:51 UTC, vedorofeev commented on php-package/src/Core/ActionCaller/ActionCaller.php
> +        var_dump($defaultParameters);
Удалить

2022-09-27 05:58 UTC, rollsover requested changes

2022-09-27 05:58 UTC, rollsover commented on php-package/src/Core/ActionCaller/ActionCaller.php
> +            $exception = new ValidateException();
ActionParameterValidateException

2022-09-27 05:58 UTC, rollsover commented on php-package/src/Model/Metadata/AbstractAttributeMetadata.php
> +abstract class AbstractAttributeMetadata
Ну так переименуйте нормально, чтобы было логично

2022-09-27 07:33 UTC, Krishtalev commented on php-package/src/Core/ActionCaller/ActionCaller.php
> +            $exception = new ValidateException();
Сделал

2022-09-27 07:33 UTC, Krishtalev commented on php-package/src/Core/ActionCaller/ActionCaller.php
> +        var_dump($defaultParameters);
Сделал

2022-09-27 07:33 UTC, Krishtalev commented on php-package/src/Model/Metadata/AbstractAttributeMetadata.php
> +abstract class AbstractAttributeMetadata
Вынес в трейт и переименовал

2022-10-18 10:38 UTC, closed without merging