3.x Add Action Policy && Restore Project Files.
egal/framework pull request #33
Opened 2022-10-13 13:14 UTC by vedorofeev

2022-10-14 04:21 UTC, rollsover requested changes

2022-10-14 04:21 UTC, rollsover commented on packages/php/src/Auth/Entities/AuthEntity.php
> +        $methodName = preg_replace("/OrFail/", '', $name);
В ругулярку конце строки добавь, чтобы точно считалось как постфикс. А лучше regex extract.

2022-10-15 02:02 UTC, vedorofeev commented on packages/php/src/Auth/Entities/AuthEntity.php
> +        $methodName = preg_replace("/OrFail/", '', $name);
Поправил: теперь используется регулярка с группами.

2022-10-15 11:47 UTC, rollsover requested changes

2022-10-15 11:47 UTC, rollsover commented on packages/php/src/AuthServiceDependencies/Models/Service.php
> +        Session::getAuthEntity()->mayOrFail(Service::class, 'login');
Переименовать:
`AuthEntity` -> `Client`

Соответственно:
`Session::getAuthEntity()` -> `Session::client()` (без `get`)

2022-10-15 11:47 UTC, rollsover commented on packages/php/src/AuthServiceDependencies/Models/User.php
>      public static function getServiceModel(): string
Удалить, оно не используется. Но проверить, везде ли не используется.

2022-10-15 11:47 UTC, rollsover commented on packages/php/src/AuthServiceDependencies/Models/User.php
>      protected function generateAuthInformation(): array
Переименовать соответственно property JWT

2022-10-15 11:47 UTC, rollsover commented on packages/php/src/AuthServiceDependencies/Models/User.php
>      protected function generateAuthInformation(): array
p.s. Это `sub`

2022-10-15 11:47 UTC, rollsover commented on packages/php/src/AuthServiceDependencies/Models/User.php
>      protected function generateAuthInformation(): array
`targetServiceName` -> `aud` (ex. `project_name.auth.service`)
`authInformation` -> `sub`
`expiredAt` -> `exp`

А также:
`iat` - заполнить

p.s. Достаточно информативная статья https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-claims

p.p.s. Не вижу изменений вообще в UST, UMT, UMRT и т.д..

2022-10-15 11:47 UTC, rollsover commented on packages/php/src/AuthServiceDependencies/Models/User.php
>      protected function generateAuthInformation(): array
`generateAuthInformation` -> `generateAuthSub`

2022-10-15 11:47 UTC, rollsover commented on packages/php/src/AuthServiceDependencies/Models/User.php
>      protected function generateAuthInformation(): array
`sub.auth_identification` -> `sub.${model.keyName}`, короче не придумывать нового, брать напрямую из модели. А при логине в сервис вытаскивать именно эту проперти из JWT.

2022-10-15 11:47 UTC, rollsover commented on packages/php/src/Core/ActionCaller/ActionCaller.php
>      private function isAccessedForCall(): bool
Убрать, дублирование кода.

2022-10-15 11:47 UTC, rollsover commented on packages/php/src/Core/Communication/Request.php
> +            ['serviceName' => config('app.service_name'), 'key' => config('app.service_key')]
Параметры должны быть всегда в снейке

2022-10-15 11:47 UTC, rollsover commented on packages/php/src/Auth/Entities/AuthEntity.php
> +    public function may(string|Model $model, string $ability): bool
Всетаки лушче:
Может ли обновить эту домель
`->may('updating', User::class)`

2022-10-15 11:47 UTC, rollsover commented on packages/php/src/Model/Traits/VariableMetadata.php
> +    public function getValidationRules(): array
Этот метод будет работать в рантайме, он должен быть очень простым. Все манипуляции перенести в сеттеры.

2022-10-17 02:36 UTC, vedorofeev commented on packages/php/src/Auth/Entities/Guest.php
> +    public function __construct() { }
Убрал.

2022-10-17 02:36 UTC, vedorofeev commented on packages/php/src/Auth/Entities/User.php
> +    public readonly string $id;
Точно, заменил.

2022-10-17 02:37 UTC, vedorofeev commented on packages/php/src/Auth/Exceptions/NoAccessForActionException.php
> +class NoAccessForActionException extends Exception
Исправил.

2022-10-17 02:39 UTC, vedorofeev commented on packages/php/src/AuthServiceDependencies/Models/Service.php
> +        Session::getAuthEntity()->mayOrFail(Service::class, 'login');
Переименовал.

2022-10-17 02:54 UTC, vedorofeev commented on packages/php/src/AuthServiceDependencies/Models/User.php
>      public static function getServiceModel(): string
Оно используется, но не вижу прямой необходимости, если базовый Service класс можно сделать не абстрактным. https://github.com/egal/framework/commit/c64a41d8d0311c8a374f2f96be993e17c95e74bd

2022-10-17 02:55 UTC, vedorofeev commented on packages/php/src/AuthServiceDependencies/Models/User.php
>      protected function generateAuthInformation(): array
Предполагал сделать это отдельным PL.

2022-10-17 02:56 UTC, vedorofeev commented on packages/php/src/Core/ActionCaller/ActionCaller.php
>      private function isAccessedForCall(): bool
Убрал..

2022-10-17 03:09 UTC, vedorofeev commented on packages/php/src/Core/Communication/Request.php
> +            ['serviceName' => config('app.service_name'), 'key' => config('app.service_key')]
Поменял. Также пришлось переименовать аргументы функций, посколько их именование соответствует тому, что передается в запросе.

2022-10-17 03:09 UTC, vedorofeev commented on packages/php/src/Core/Communication/Request.php
> +            ['serviceName' => config('app.service_name'), 'key' => config('app.service_key')]
https://github.com/egal/framework/commit/476380deebff3b5bc0c4b380e152f09423f660e7

2022-10-17 03:23 UTC, vedorofeev commented on packages/php/src/Auth/Entities/AuthEntity.php
> +    public function may(string|Model $model, string $ability): bool
Поменял местами.

2022-10-17 03:27 UTC, vedorofeev commented on packages/php/src/Model/Traits/VariableMetadata.php
> +    public function getValidationRules(): array
Перенес в сеттер.

2022-10-17 15:11 UTC, rollsover commented on packages/php/src/AuthServiceDependencies/Models/User.php
>      public static function getServiceModel(): string
Модель сервиса не изменная

2022-10-17 15:11 UTC, rollsover commented on packages/php/src/AuthServiceDependencies/Models/User.php
>      protected function generateAuthInformation(): array
Кк, нужна TODO

2022-10-17 15:22 UTC, rollsover requested changes

2022-10-17 15:22 UTC, rollsover commented on packages/php/src/Model/Traits/VariableMetadata.php
> +    public function setValidationRules(): void
Не `set`, а какой-нибудь `construct` или `append`. И такие методы делают `protected`, так как они служебные для кода, а пользователь может их просто так вызвать.

2022-10-17 15:22 UTC, rollsover commented on stand/server/auth-service/app/Models/Employee.php
> +                FieldMetadata::make('address', VariableType::STRING)
Ненененене, отнаслейду `FieldType` от `VariableType` и используй тут `FieldType`!

2022-10-18 04:00 UTC, vedorofeev commented on packages/php/src/AuthServiceDependencies/Models/User.php
>      protected function generateAuthInformation(): array
Добавил TODO

2022-10-18 04:18 UTC, vedorofeev commented on packages/php/src/Model/Traits/VariableMetadata.php
> +    public function setValidationRules(): void
Переименовал в `constructValidationRules` и сделал метод `protected`

2022-10-18 06:32 UTC, vedorofeev commented on stand/server/auth-service/app/Models/Employee.php
> +                FieldMetadata::make('address', VariableType::STRING)
Оставил TODO.

2022-10-18 06:38 UTC, rollsover approved these changes

2022-10-18 06:39 UTC, merged