Server Addition stand project with full DB schema
egal/framework pull request #8
Opened 2022-09-08 14:53 UTC by Krishtalev

DB schema

2022-09-09 04:37 UTC, rollsover requested changes
Переложить все диаграммы в отдельный plantuml файл, без md.
Сгруппировать все схемы в одну используя `database main-service {...}`.
Доделать схему до нормальной физической модели (m2m не существует в физической и другое). Все PNG удалить. README.md откатить

2022-09-09 06:49 UTC, rollsover requested changes
Прогнать через Storm, чтобы офрмление было идентичное везде

2022-09-09 06:49 UTC, rollsover commented on stand/dbschema.puml
> +@enduml
Пустая строка в конце

2022-09-09 06:49 UTC, rollsover commented on stand/dbschema.puml
> +  *name
Тип

2022-09-09 07:04 UTC, rollsover requested changes
Связи между сервисами (пользователь и спикер/студент) (чат и лессон/лессонРеквест).

2022-09-22 03:12 UTC, vedorofeev commented
Залито в рамках PL метаданных

2022-09-22 03:12 UTC, closed without merging