3 Add server model metadata on classes.
egal/framework pull request #9
Opened 2022-09-09 08:49 UTC by vedorofeev

2022-09-12 03:36 UTC, rollsover requested changes
И не вижу настройку модели на основании метаданных.

2022-09-12 03:36 UTC, rollsover commented on php-package/src/Model/Enums/FieldTypeEnum.php
> +    case DATETIME = DateTime::class;
Без сторонних классов тут

2022-09-12 03:36 UTC, rollsover commented on php-package/src/Model/Enums/FieldTypeEnum.php
> +    case DATETIME = DateTime::class;
toArray() работает не корректно.

2022-09-12 03:36 UTC, rollsover commented on php-package/src/Model/ModelMetadataManager.php
> +    protected function scanModels(?string $dir = null): void
Сделай параметрами полную директорию до моделей и указание неймспейса

2022-09-12 03:36 UTC, rollsover commented on php-package/src/Model/ModelMetadataManager.php
> +    public static function getInstance(): ModelMetadataManager
Почему тут статичные функции до сих пор, если это уже фасад?

2022-09-12 03:36 UTC, rollsover commented on php-package/src/Model/ModelMetadataManager.php
> +class ModelMetadataManager
Добавить registerModel и registerDir

2022-09-12 05:38 UTC, vedorofeev commented on php-package/src/Model/ModelMetadataManager.php
> +class ModelMetadataManager
registerDir - это же scanDir($dir = )

2022-09-12 05:39 UTC, vedorofeev commented on php-package/src/Model/ModelMetadataManager.php
> +    public static function getInstance(): ModelMetadataManager
исправил

2022-09-12 05:39 UTC, vedorofeev commented on php-package/src/Model/Enums/FieldTypeEnum.php
> +    case DATETIME = DateTime::class;
как без сторонних классов указать тип uuid и DateTime

2022-09-12 08:04 UTC, rollsover requested changes

2022-09-12 08:04 UTC, rollsover commented on stand/server/auth-service/app/Models/Modelss/Service.php
> + * @action loginToService   {@statuses-access guest}
Также убрать, зарегистрировать новым способом

2022-09-12 08:04 UTC, rollsover commented on php-package/src/Model/Model.php
> +    public abstract static function constructMetadata();
Конструктор абстрактным и в трейт, а getter финальным и в трейт

2022-09-12 08:04 UTC, rollsover commented on stand/server/auth-service/app/Models/Service.php
> -class Service extends BaseService
Почему удалил?

2022-09-12 08:04 UTC, rollsover commented on stand/server/auth-service/app/Models/User.php
> +    public static function getMetadata(): array
Реализация должна быть в базовой модели

2022-09-12 08:13 UTC, vedorofeev commented on php-package/src/Core/ActionCaller/ActionCaller.php
> +        $this->modelMetadata = ModelMetadataManager::getModelMetadata(static::class);
вернул 
также заметил отутствие имплементации $this->modelMetadata->getAction, беру на реализацию

2022-09-12 08:17 UTC, vedorofeev commented on php-package/src/Model/Enums/FieldTypeEnum.php
> +    case DATETIME   = 'datetime';
добавил

2022-09-12 08:18 UTC, vedorofeev commented on php-package/src/Model/Enums/ValidationRulesEnum.php
> +enum ValidationRulesEnum: string
в ларке проверки isValidatable написаны через in_array: https://github.com/illuminate/validation/blob/master/Validator.php
оставили так

2022-09-12 08:32 UTC, vedorofeev commented on php-package/src/Model/Model.php
> +    public abstract static function constructMetadata();
перенёс

2022-09-12 08:33 UTC, vedorofeev commented on php-package/src/Model/ModelMetadataManager.php
> +class ModelMetadataManager
добавил

2022-09-12 08:38 UTC, vedorofeev commented on php-package/src/Model/ModelMetadataManager.php
> +            $this->modelsMetadata[$class] = call_user_func(array($class, 'constructMetadata'));
исправил

2022-09-12 08:41 UTC, vedorofeev commented on php-package/src/Model/ServiceProvider.php
> +        $this->app->singleton('modelMetadataManager', function (): ModelMetadataManager {
Поменял

2022-09-12 08:47 UTC, vedorofeev commented on php-package/src/Model/ServiceProvider.php
> +        ModelMetadataManagerFacade::registerDir('/app/app/Models/', 'App\Models\\');
перенес в AppServiceProvider сервиса авторизации

2022-09-12 09:21 UTC, vedorofeev commented on stand/server/auth-service/app/Models/User.php
> +    public static function getMetadata(): array
перенес

2022-09-13 05:05 UTC, vedorofeev commented on stand/server/auth-service/app/Models/Employee.php
>  /**
убарл

2022-09-13 05:05 UTC, vedorofeev commented on stand/server/auth-service/app/Models/Modelss/Service.php
> + * @action loginToService   {@statuses-access guest}
убрал

2022-09-13 05:05 UTC, vedorofeev commented on stand/server/auth-service/app/Models/Service.php
> -class Service extends BaseService
вернул

2022-09-13 10:35 UTC, rollsover requested changes

2022-09-13 10:35 UTC, rollsover commented on php-package/src/Model/Enums/FieldTypeEnum.php
> +    case FLOAT      = 'float';
Убрать `float`

2022-09-13 10:35 UTC, rollsover commented on php-package/src/Model/Filter/FilterConditions/SimpleFilterConditionApplier.php
> -            $relationModelMetadata->validateFieldValueType($field, $value);
TODO оставь

2022-09-13 10:35 UTC, rollsover commented on php-package/src/Model/Filter/FilterConditions/SimpleFilterConditionApplier.php
> -        $modelMetadata->validateFieldValueType($field, $value);
TODO на реверт

2022-09-13 10:35 UTC, rollsover commented on php-package/src/Model/Traits/UsesModelMetadata.php
> +    public function getRelations(): array
Не проверено

2022-09-13 10:35 UTC, rollsover commented on stand/server/auth-service/database/seeders/DatabaseSeeder.php
> +        $this->call(AdminRoleSeeder::class);
Тут вроде как можно массивом передать

2022-09-14 05:38 UTC, vedorofeev commented on php-package/src/Model/ModelMetadataManager.php
> +    protected function scanModels(?string $dir = null): void
вынес в отдельный метод registerDir и registerModel

2022-09-14 05:39 UTC, vedorofeev commented on php-package/src/Model/Model.php
> +    public abstract static function constructMetadata();
Добавил

2022-09-14 05:41 UTC, vedorofeev commented on php-package/src/Model/Enums/FieldTypeEnum.php
> +    case FLOAT      = 'float';
убрал

2022-09-14 05:42 UTC, vedorofeev commented on php-package/src/Model/Filter/FilterConditions/SimpleFilterConditionApplier.php
> -            $relationModelMetadata->validateFieldValueType($field, $value);
оставил

2022-09-14 05:45 UTC, vedorofeev commented on php-package/src/Model/Filter/FilterConditions/SimpleFilterConditionApplier.php
> -        $modelMetadata->validateFieldValueType($field, $value);
создал TODO

2022-09-14 05:46 UTC, vedorofeev commented on stand/server/auth-service/database/seeders/DatabaseSeeder.php
> +        $this->call(AdminRoleSeeder::class);
нет, к сожалению
public function Seeder::call($class, $silent = false, array $parameters = []) Seeder

2022-09-15 07:24 UTC, vedorofeev commented on php-package/src/Model/Traits/UsesModelMetadata.php
> +        if (in_array($fieldType, $fieldValidationRules)) {
Стоит ли тип филда добавлять к валидации полей

2022-09-15 07:57 UTC, rollsover requested changes

2022-09-15 07:57 UTC, rollsover commented on php-package/src/Model/Enums/RelationType.php
> +    case HAS_ONE = 'hasOne';
В снейк-кейсе

2022-09-15 07:57 UTC, rollsover commented on php-package/src/Model/Metadata/ModelMetadata.php
> +    public function getFillable(): array
getFillableFieldsNames() - перименовать
и типизировать возвращаемый тип string[]

Идентично для аналогичных методов

2022-09-15 07:57 UTC, rollsover commented on php-package/src/Model/ModelMetadataManager.php
> +    public function registerDir(string $dir, string $modelsNamespace): void
Переименовать в `registerDirectory()`

2022-09-15 07:57 UTC, rollsover commented on php-package/src/Model/ServiceProvider.php
> +        $this->app->singleton('modelMetadataManager', fn () => new ModelMetadataManager());
`modelMetadataManager` -> `ModelMetadataManager`

2022-09-15 07:57 UTC, rollsover commented on php-package/src/Model/Traits/UsesModelMetadata.php
> +        if (in_array($fieldType, $fieldValidationRules)) {
Стоит, но у тебя и так будет 100%

такую логику в геттерах не делать, из-за соображений производительности

2022-09-15 07:57 UTC, rollsover commented on php-package/src/Model/Traits/UsesModelMetadata.php
> +        return $this->modelMetadata->getPrimaryKey()->getType()->value;
Пихнуть сеттером в конструкторе модели (инициализаторе трейта)

2022-09-15 07:57 UTC, rollsover commented on php-package/src/Model/Traits/UsesValidator.php
> +        $primaryKey = $this->getModelMetadata()->getPrimaryKey()->getName();
Пробежаться надо по коду и везде где статично указано id - заменить через подобную логику. Также касается id в actionUpdate*, тут будет как параметр - `key`

2022-09-15 07:57 UTC, rollsover commented on stand/server/auth-service/app/Models/Employee.php
>      use UsesUuidKey;
Логику этого трейта в конструктор перенести на основании метаданных

2022-09-16 06:19 UTC, vedorofeev commented on php-package/src/Model/Metadata/ModelMetadata.php
> +    public function getFillable(): array
переименовал

2022-09-16 06:20 UTC, vedorofeev commented on php-package/src/Model/Metadata/ModelMetadata.php
> +    public function getFillable(): array
и типизировал возвращаемый тип

2022-09-16 06:21 UTC, vedorofeev commented on php-package/src/Model/ModelMetadataManager.php
> +    public function registerDir(string $dir, string $modelsNamespace): void
сделано

2022-09-16 06:21 UTC, vedorofeev commented on php-package/src/Model/ServiceProvider.php
> +        $this->app->singleton('modelMetadataManager', fn () => new ModelMetadataManager());
Переименовано

2022-09-19 03:41 UTC, vedorofeev commented on php-package/src/Model/Traits/UsesValidator.php
> +        $primaryKey = $this->getModelMetadata()->getPrimaryKey()->getName();
Пока что не менял именование параметра, хотелось бы обсудить, насколько везде это нужно сделать, например, нужно ли менять $id на $key в исключениях, во внутренней логике, не в экшнах

2022-09-19 04:11 UTC, vedorofeev commented on stand/server/auth-service/app/Models/Employee.php
>      use UsesUuidKey;
перенес

2022-09-19 04:11 UTC, vedorofeev commented on php-package/src/Model/Traits/UsesModelMetadata.php
> +        return $this->modelMetadata->getPrimaryKey()->getType()->value;
перенес

2022-09-19 04:11 UTC, vedorofeev commented on php-package/src/Model/Enums/RelationType.php
> +    case HAS_ONE = 'hasOne';
поменял кейс

2022-09-19 04:12 UTC, vedorofeev commented on php-package/src/Model/Traits/UsesModelMetadata.php
> +        if (in_array($fieldType, $fieldValidationRules)) {
перенес

2022-09-19 05:38 UTC, rollsover commented on php-package/composer.json
> +        "laravel/lumen-framework": "v9.1.2",
Фикс версия - нельзя

2022-09-19 05:38 UTC, rollsover commented on php-package/src/Core/ActionCaller/ActionCaller.php
> +//            $this->actionParameters
Куда?

2022-09-19 05:38 UTC, rollsover commented on php-package/src/Core/ActionCaller/ActionCaller.php
> +//            $this->actionParameters
Убери

2022-09-19 05:38 UTC, rollsover commented on php-package/src/Core/ActionCaller/ActionCaller.php
>          foreach ($this->modelActionMetadata->getParameters() as $reflectionParameter) {
Убрать старую реализацию, оставь ТУДУ

2022-09-19 06:26 UTC, vedorofeev commented on php-package/composer.json
> +        "laravel/lumen-framework": "v9.1.2",
поменял на `^9`

2022-09-19 06:34 UTC, vedorofeev commented on php-package/src/Core/ActionCaller/ActionCaller.php
> +//            $this->actionParameters
убрал

2022-09-19 06:43 UTC, vedorofeev commented on php-package/src/Core/ActionCaller/ActionCaller.php
>          foreach ($this->modelActionMetadata->getParameters() as $reflectionParameter) {
Добавил много ТУДУ

2022-09-19 10:37 UTC, merged